FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY SmartStorage.sln .
COPY SmartStorage.Core/*.csproj ./SmartStorage.Core/
COPY SmartStorage.Infrastructure/*.csproj ./SmartStorage.Infrastructure/
COPY SmartStorage/*.csproj ./SmartStorage/

RUN dotnet restore

COPY . .

RUN dotnet publish SmartStorage/SmartStorage.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .
ENV ASPNETCORE_URLS=http://+:10000
EXPOSE 10000
ENTRYPOINT ["dotnet", "SmartStorage.dll"]